id: P000495
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ65553
  title: གསུང་ཐོར་བུ། བློ་བཟང་འོད་ཟེར།
  author: ''
  volumes:
    88b78eed3ab34835ab71560baf02d6ee:
      image_group_id: I4CZ65583
      title: Volume 1 of gsung thor bu/ blo bzang 'od zer/
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
